Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20170731.0.0"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "172.18.161.7"
  config.vm.provider "virtualbox" do |p|
    p.cpus = "8"
    p.memory = "16384"
  end
  config.vm.provision "shell", path: "provision.sh"
end
