Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20170731.0.0"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.34.101"
  config.vm.provider "virtualbox" do |p|
    p.cpus = "2"
    p.memory = "4096"
  end
  config.vm.provision "shell", path: "provision.sh"
end
