Vagrant.configure("2") do |config|
  config.vm.define "os-controller" do |d|
    d.vm.box = "ubuntu/xenial64"
    d.vm.box_version = "20170731.0.0"
    d.vm.box_check_update = false
    d.vm.network "private_network", ip: "172.18.161.101"
    d.vm.provider "virtualbox" do |p|
      p.cpus = "2"
      p.memory = "4096"
    end
    d.vm.provision "shell", path: "provision-os-controller.sh"
  end

  config.vm.define "os-network" do |d|
    d.vm.box = "ubuntu/xenial64"
    d.vm.box_version = "20170731.0.0"
    d.vm.box_check_update = false
    d.vm.network "private_network", ip: "172.18.161.102"
    d.vm.provider "virtualbox" do |p|
      p.cpus = "1"
      p.memory = "2048"
    end
    d.vm.provision "shell", path: "provision-os-network.sh"
  end

  config.vm.define "os-compute" do |d|
    d.vm.box = "ubuntu/xenial64"
    d.vm.box_version = "20170731.0.0"
    d.vm.box_check_update = false
    d.vm.network "private_network", ip: "172.18.161.103"
    d.vm.provider "virtualbox" do |p|
      p.cpus = "2"
      p.memory = "4096"
    end
    d.vm.provision "shell", path: "provision-os-compute.sh"
  end

  config.vm.define "odl-controller" do |d|
    d.vm.box = "ubuntu/xenial64"
    d.vm.box_version = "20170731.0.0"
    d.vm.box_check_update = false
    d.vm.network "private_network", ip: "172.18.161.104"
    d.vm.provider "virtualbox" do |p|
      p.cpus = "2"
      p.memory = "4096"
    end
    d.vm.provision "shell", path: "provision-odl-controller.sh"
  end

end
